<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        body {
            background-color: rgba(0, 0, 0, 0.09);
            padding: 5px 30px 30px 30px;
        }

        .promise {
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            margin: auto;
        }

        .title {
            text-align: center;
            font-size: 23px;
            font-weight: bold;
        }

        .title span {
            font-size: 15px;
        }

        .paragraph {
            text-indent: 2em
        }

        .warnColor {
            color: red;
        }

        .wordColor {
            color: firebrick;
        }

        .block {
            display: block;
        }

        .coding {
            border-radius: 5px;
            padding: 20px;
            width: 700px;
            height: auto;
            background-color: #000000;
            color: green;
        }
    </style>
</head>
<body>
<div class="promise">
    <p class="title">Promise ---<span>承诺，表示其他手段无法改变</span></p>
    <p>含义：</p>
    <p class="paragraph">
        <span class="wordColor">Promise</span>是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和强大。
        它由社区最早提出和实现，ES6将其写进了语言标准，统一了用法，原生提供了<span class="wordColor">Promise</span>对象。
    </p>
    <p class="paragraph">
        所谓<span class="wordColor">Promise</span>，简单说就是一个容器，里面保存着某个未来才会结束的事件(通常是一个异步操作)的结果。
        从语法上说，<span class="wordColor">Promise</span>是一个对象，从它可以获取异步操作的消息。
        <span class="wordColor">Promise</span>提供统一的<span class="wordColor">API</span>，各种异步操作都可以用同样的方法进行处理。
    </p>
    <div class="paragraph">
        <span class="wordColor">Promise</span>对象有以下两个特点：
        <p>
            (1)对象的状态不受外界影响。
            <span class="wordColor">Promise</span>对象代表一个异步操作，有三种状态：<span class="wordColor"><span class="wordColor">pending</span></span>，
            <span class="wordColor">fulfilled</span>，<span class="wordColor">rejected</span>
            只有异步操作的结果可以决定当前是哪一种状态，任何其他的操作都无法改变这个状态。
        </p>
        <p>
            (2)一旦状态改变，就不会再变，任何时候都可以得到这个结果。
            两种可能：<span class="wordColor">pending</span> -> <span class="wordColor">fulfilled</span>
            <span class="wordColor">pending</span> -> <span class="wordColor">rejected</span>
            只要这两种状态发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就成<span class="wordColor">resolved</span>(已定型)
            如果改变已经发生了，你再对<span class="wordColor">Promise</span>对象添加回调函数，也会立即得到这个结果。
            <span class="wordColor">
                ---这跟事件Event完全不同，事件的特点是，如果你错过了它，再去监听是得不到结果的。
            </span>
        </p>
        <a style="color: blueviolet;text-decoration: underline; display: block"
           onclick="window.open('https://github.com/es6-org/exploring-es6/blob/master/md/24.10.md')">Promise对象优缺点:</a>
        <p>
            优点：
            <span class="block">a.可以将异步操作以同步操作的流程表达出来</span>
            <span class="block">b.避免了层层嵌套的回调函数</span>
            <span class="block">c.提供统一接口，使得控制异步操作更加容易</span>
        </p>
        <p>
            缺点：
            <span class="block">a.无法取消<span class="wordColor">Promise</span>，一旦新建它就会立即执行，无法中途取消。</span>
            <span class="block">b.如果不设置回调函数，<span class="wordColor">Promise</span>内部抛出的错误，不会反应到外部</span>
            <span class="block">c.当处于<span class="wordColor">pending</span>状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）</span>
        </p>
    </div>
    <hr/>
    <p>基本用法:</p>
    <div class="paragraph">
        <p>
            Promise对象是一个构造函数，用来生成<span class="wordColor">Promise实例</span>。
        </p>
        <pre class="coding">const promise = new Promise(<span class="wordColor">function(resolve, reject){
                if(/*异步操作成功*/){
                    resolve(value);
                }else{
                    reject(error);
                }</span>
            })
        </pre>
        <p>Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。</p>
        <p>resolve：将Promise对象的状态从"未完成"变为"成功"（pending -> fulfilled），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；</p>
        <p>reject：将Promise对象的状态从"未完成"变为"成功"（pending -> rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。</p>
        <p>Promise实例生成以后，可以用then方法分别指定fulfilled状态和rejected状态的回调函数。</p>
        <pre class="coding">promise.then(function(value) {
                // success
            }, function(error) {
                // failure
            });
        </pre>
        <p>
            then方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为fulfilled时调用，
            第二个回调函数是Promise对象的状态变为rejected时调用。
            其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。
        </p>
        <pre class="coding">function timeout(ms) {
            return new Promise((resolve, reject) => {
            setTimeout(resolve, ms, 'done');
            });
            }

            timeout(100).then((value) => {
            console.log(value);
            });
        </pre>
        <p>上面代码中，timeout方法返回一个Promise实例，表示一段时间以后才会发生的结果。过了指定的时间（ms参数）以后，
            Promise实例的状态变为resolved，就会触发then方法绑定的回调函数。</p>
        <p>Promise 新建后就会立即执行。</p>
        <p>下面是异步加载图片的例子</p>
        <pre class="coding">function loadImageAsync(url) {
        return new Promise(function(resolve, reject) {
            const image = new Image();

            image.onload = function() {
                resolve(image);
            };

            image.onerror = function() {
                reject(new Error('Could not load image at ' + url));
            };

            image.src = url;
        });
    }
        </pre>
        <p>上面代码中，使用Promise包装了一个图片加载的异步操作。如果加载成功，就调用resolve方法，否则就调用reject方法。</p>
        <p>下面是一个用Promise对象实现的 Ajax 操作的例子。</p>
        <pre class="coding">const getJSON = function(url) {
        const promise = new Promise(function(resolve, reject){
            const handler = function() {
                if (this.readyState !== 4) {
                    return;
                }
                if (this.status === 200) {
                    resolve(this.response);
                } else {
                    reject(new Error(this.statusText));
                }
            };
            const client = new XMLHttpRequest();
            client.open("GET", url);
            client.onreadystatechange = handler;
            client.responseType = "json";
            client.setRequestHeader("Accept", "application/json");
            client.send();

        });

        return promise;
    };

    getJSON("/posts.json").then(function(json) {
        console.log('Contents: ' + json);
    }, function(error) {
        console.error('出错了', error);
    });
        </pre>
    </div>
    <p>Promise.prototype.then()</p>
    <div class="paragraph">
        <p>then方法的第一个参数是resolved状态的回调函数，第二个参数（可选）是rejected状态的回调函数。</p>
        <p>then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。</p>
    </div>
    <div style="display: flex; background-color: #000000;border-radius: 5px">
        <pre style="color: green;">
            getJSON("/post/1.json").then(function(post) {
            return getJSON(post.commentURL);
            }).then(function funcA(comments) {
            console.log("resolved: ", comments);
            }, function funcB(err){
            console.log("rejected: ", err);
            });
        </pre>
        <div style="color: blue; position: relative;left: 4%;top: 50px;">
            ====>
            ====>
        </div>
        <pre style="color: #ff0000;">
            getJSON("/post/1.json").then(
            post => getJSON(post.commentURL)
            ).then(
            comments => console.log("resolved: ", comments),
            err => console.log("rejected: ", err)
            );
        </pre>
    </div>
    <p>then方法指定的回调函数，如果运行中抛出错误，也会被catch方法捕获。</p>

    <div class="coding">
        <pre>
            p.then((val) => console.log('fulfilled:', val))
            .catch((err) => console.log('rejected', err));

            // 等同于
            p.then((val) => console.log('fulfilled:', val))
            .then(null, (err) => console.log("rejected:", err));
        </pre>
    </div>

    <p>如果 Promise 状态已经变成resolved，再抛出错误是无效的。</p>
    <div class="coding">
        <pre>const promise = new Promise(function(resolve, reject) {
              resolve('ok');
              throw new Error('test');
            });
            promise
              .then(function(value) { console.log(value) })
              .catch(function(error) { console.log(error) });
            // ok
        </pre>
        Promise 在resolve语句后面，再抛出错误，不会被捕获，等于没有抛出。因为 Promise 的状态一旦改变，就永久保持该状态，不会再变了。
    </div>
    <p>Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。</p>
    <div class="coding">
        <pre>
            getJSON('/post/1.json').then(function(post) {
              return getJSON(post.commentURL);
            }).then(function(comments) {
              // some code
            }).catch(function(error) {
              // 处理前面三个Promise产生的错误
            });
        </pre>
        <p>一共有三个 Promise对象：一个由getJSON产生，两个由then产生。它们之中任何一个抛出的错误，都会被最后一个catch捕获。</p>
    </div>
    <p>不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。</p>
    <div class="coding">
        <pre>
            // bad
            promise
              .then(function(data) {
                // success
              }, function(err) {
                // error
              });

            // good
            promise
              .then(function(data) { //cb
                // success
              })
              .catch(function(err) {
                // error
              });
        </pre>
        <p>第二种写法要好于第一种写法，理由是第二种写法可以捕获前面then方法执行中的错误，也更接近同步的写法（try/catch）。
            因此，建议总是使用catch方法，而不使用then方法的第二个参数。</p>
    </div>
    <p>Promise 内部的错误不会影响到 Promise 外部的代码.会打印错误提示但是不会退出进程，终止脚本执行。这个脚本放在服务器执行，退出码就是0（即表示执行成功）</p>
    <hr/>
    <p>Promise.prototype.finally() ----finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的</p>
    <div class="coding">
        <pre>
            promise
            .then(result => {···})
            .catch(error => {···})
            .finally(() => {···});
        </pre>

        <p>服务器使用 Promise 处理请求，然后使用finally方法关掉服务器。</p>
        <pre>
            server.listen(port)
              .then(function () {
                // ...
              })
              .finally(server.stop);
        </pre>
        <p>finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected。
            这表明，finally方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果。</p>
    </div>
    <p>
        实现finally,不管前面的 Promise 是fulfilled还是rejected，都会执行回调函数callback。finally方法总是会返回原来的值
    </p>
    <div class="coding">
        <pre>
            Promise.prototype.finally = function (callback) {
              let P = this.constructor;
              return this.then(
                value  => P.resolve(callback()).then(() => value),
                reason => P.resolve(callback()).then(() => { throw reason })
              );
            };
        </pre>
    </div>
    <p>Promise.all() --用于将多个Promise实例包装成一个新的Promise实例</p>
    <div class="coding">
        const p = Promise.all([pa,p2,p3])
    </div>
    <p>
        Promise.all()接受一个数组作为参数，p1,p2,p3都是Promise实例，如果不是就会先调用Promise.resolve方法，将参数转为 Promise 实例，再进一步处理。
        （Promise.all方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。）
    </p>
    <p>
        p的状态由p1、p2、p3决定，分成两种情况。
    <p>(1)只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。</p>

    <p>(2)只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。</p>
    <div class="coding">
        <pre>
            // 生成一个Promise对象的数组
            const promises = [2, 3, 5, 7, 11, 13].map(function (id) {
              return getJSON('/post/' + id + ".json");
            });

            Promise.all(promises).then(function (posts) {
              // ...
            }).catch(function(reason){
              // ...
            });
        </pre>
    </div>
    <p>上面代码中，promises是包含 6 个 Promise 实例的数组，只有这 6 个实例的状态都变成fulfilled，或者其中有一个变为rejected，才会调用Promise.all方法后面的回调函数。</p>
    <p>如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。
        如果没有自己的catch方法，就会调用Promise.all()的catch方法。</p>
    <p>Promise.race()----同样是将多个 Promise 实例，包装成一个新的 Promise 实例。</p>
    <div class="coding">
        const p = Promise.race([p1, p2, p3]);
        <p>上面代码中，只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。
            Promise.race方法的参数与Promise.all方法一样</p>
        <p>下面是一个例子，如果5秒之内fetch方法无法返回结果，变量p的状态就会变为rejected，从而触发catch方法指定的回调函数.否则变为resolve。</p>
        <pre>
            const p = Promise.race([
              fetch('/resource-that-may-take-a-while'),
              new Promise(function (resolve, reject) {
                setTimeout(() => reject(new Error('request timeout')), 5000)
              })
            ]);

            p
            .then(console.log)
            .catch(console.error);
        </pre>
    </div>
    <p>Promise.resolve() -----将现有对象转为 Promise 对象</p>
    <div class="coding">
        const jsPromise = Promise.resolve($.ajax('/whatever.json'));

        Promise.resolve('foo')
        // 等价于
        new Promise(resolve => resolve('foo'))
    </div>
    <p>
        Promise.resolve方法的参数分成四种情况。
    </p>
    <p>(1)参数是 Promise 实例，Promise.resolve不做任何修改、原封不动地返回这个实例。</p>
    <p>(2)参数是一个thenable对象，方法会将这个对象转为 Promise 对象，然后就立即执行thenable对象的then方法。
    <pre class="coding">
            let thenable = {
              then: function(resolve, reject) {
                resolve(42);
              }
            };

            let p1 = Promise.resolve(thenable);
            p1.then(function(value) {
              console.log(value);  // 42
            });
    </pre>
    <p>thenable对象的then方法执行后，对象p1的状态就变为resolved，从而立即执行最后那个then方法指定的回调函数，输出 42。</p>
    </p>
    <p>(3)参数不是具有then方法的对象，或根本就不是对象(如果参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的 Promise 对象，状态为resolved)</p>
    <p>(4)不带有任何参数(调用时不带参数，直接返回一个resolved状态的 Promise 对象。)
    <pre class="coding">
    const p = Promise.resolve();

    p.then(function () {
      // ...
    });
    <hr/>
    setTimeout(function () {
      console.log('three');
    }, 0);

    Promise.resolve().then(function () {
      console.log('two');
    });

    console.log('one');

    // one
    // two
    // three
    </pre>
    <span style="display: block">setTimeout(fn, 0)在下一轮“事件循环”开始时执行，Promise.resolve()在本轮“事件循环”结束时执行，console.log('one')则是立即执行，因此最先输出。</span>
    </p>
    <p>Promise.reject()</p>
    <p>Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected</p>
    <pre class="coding">
        const p = Promise.reject('出错了');
        // 等同于
        const p = new Promise((resolve, reject) => reject('出错了'))

        p.then(null, function (s) {
        console.log(s)
        });
        // 出错了

        上面代码生成一个 Promise 对象的实例p，状态为rejected，回调函数会立即执行。
    </pre>
    <p>Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数。这一点与Promise.resolve方法不一致。</p>
    <pre class="coding">
        const thenable = {
        then(resolve, reject) {
        reject('出错了');
        }
        };

        Promise.reject(thenable)
        .catch(e => {
        console.log(e === thenable)
        })
        // true
    </pre>
    <p>Promise.reject方法的参数是一个thenable对象，执行以后，后面catch方法的参数不是reject抛出的“出错了”这个字符串，而是thenable对象</p>
    <p>
        将图片的加载写成一个Promise，一旦加载完成，Promise的状态就发生变化。
    </p>
    <pre class="coding">
        const preloadImage = function (path) {
        return new Promise(function (resolve, reject) {
        const image = new Image();
        image.onload  = resolve;
        image.onerror = reject;
        image.src = path;
        });
        };
    </pre>
</div>
<script>
    function timeout(ms) {
        return new Promise((resolve, reject) => {
            setTimeout(resolve, ms, 'done');
        });
    }

    timeout(100).then((value) => {
        console.log(value);
    });

    function loadImageAsync(url) {
        return new Promise(function (resolve, reject) {
            const image = new Image(200, 200);
            image.onload = function () {
                resolve(image);
            };
            image.onload = function () {
                // reject(new Error('Could not load image at ' + url));
            };
            image.src = url;
        })
    }

    // loadImageAsync('http://www.chinanews.com/cul/2018/01-08/U322P4T8D8418615F107DT20180108102000.jpg')

    //用promise实现ajax
    // const getJSON = function (url) {
    //     const promise = new Promise(function (resolve, reject) {
    //         const handler = function () {
    //             if(this.readyState !== 4){
    //                 return
    //             }
    //             if(this.status === 200){
    //                 resolve(this.response);
    //             }else{
    //                 reject(new Error(this.statusText))
    //             }
    //         };
    //         const client = new XMLHttpRequest();
    //         client.open("GET",url);
    //         client.onreadystatechange = handler;
    //         client.responseType = 'json';
    //         client.setRequestHeader("Accept","application/json");
    //         client.send();
    //     });
    //     return promise;
    // }
    // getJSON("/posts.json").then(function (json) {
    //     console.log('Contents:'+ json);
    // },function (error) {
    //     console.error('出错了',error)
    // })
    // getJSON("/post/1.json").then(
    //     post => getJSON(post.commentURL)
    // ).then(
    //     comments => console.log("resolved: ",comments),
    //     err => console.log("rejected: ",err)
    // )


    const promise = new Promise(function (resolve, reject) {
        try {
            throw new Error('test test');
        } catch (e) {
            reject(e);
        }
    });
    promise.catch(function (error) {
        console.log(error, 111);
    });
    //等同于   reject方法的作用，等同于抛出错误
    const promise1 = new Promise(function (resolve, reject) {

        resolve(new Error('success'));
        // reject(new Error('test'));
    });

    //抓异常，同上。 若改为resolve(new Error('test'))则应用then
    // promise1.then(function (error) {
    //     console.log(error,333)
    // }).catch(function(error) {
    //     console.log(error, 222);
    // });
    promise1.catch(function (error) {
        console.log(error, 222);
    });
</script>
</body>
</html>